---
- name: Run Custom module
  hosts: all
  become: true
  become_method: sudo

  # Gather Fatc
  pre_tasks:

  - name: "Gather fact"
    setup:
      filter:
      - 'ansible_os_family'

  tasks:

  # check OS Type
  - name: "Check OS Type"
    fail:
      msg: The system is not Solaris
    when: ( ansible_os_family != "Solaris" )

  # run custom
  - name: Gather facts dladm link
    dladm_show_facts:
      attribute: 'link'

  - name: Gather facts dladm ether
    dladm_show_facts:
      attribute: 'ether'

  - name: Gather facts dladm phys
    dladm_show_facts:
      attribute: 'phys'

  - name: set fact for print
    set_fact:
      net0_state: "{{ ansible_facts.dladm_link_list | selectattr('LINK','equalto', 'net0' ) | map(attribute='STATE') | first }}"
      net0_speed_duplex: "{{ ansible_facts.dladm_ether_list | selectattr('LINK','equalto', 'net0' ) | map(attribute='SPEED-DUPLEX') | first }}"
      net0_device: "{{ ansible_facts.dladm_phys_list | selectattr('LINK','equalto', 'net0' ) | map(attribute='DEVICE') | first }}"

  - name: print state, device and speed-duplex of net0
    debug:
      msg: "net0 is {{net0_state}} on {{net0_device}} at {{net0_speed_duplex}} speed"
